# Generated by Django 4.1.1 on 2022-10-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorialcategory_tutorial_tutorial_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 21, 46, 6, 439908), verbose_name='date published'),
        ),
    ]
